config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'homes#index'
  
  get 'Home', :to => 'homes#index'
  get 'my_tweets', :to => 'tweets#my_tweets'
  get 'users', :to => 'users#index'
  post 'follow', :to => 'users#follow'
  get 'my_follows', :to => 'followers#my_follows'
  get 'my_profile', :to => 'users#my_profile'
  




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower < ApplicationRecord
	belongs_to :user
	
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :users
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :followers
  has_many :following, :foreign_key => :follower_id, :class_name => "Follower"
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :authenticate_user!


	
  def my_follows
	@my_followers = current_user.followers
	#abort(@my_followers.inspect)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index

  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def my_tweets
  	@tweets = current_user.tweets.order('tweets.created_at desc')
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  	@users = User.all.where.not(:id => current_user.id)
  end

	
  def follow
    if params[:user_id].present?

      user = User.find_by(:id => params[:user_id])
      if user.present?

        already_follower = current_user.followers.where(:user_id=>current_user.id, :follower_id => params[:user_id])

        if already_follower.present?
            @response = {:status=>true, :msg=>"Already following"}

        else

            follower = Follower.create({ :user_id => current_user.id, :follower_id => params[:user_id] })

            if follower.id.present?
              @response = {:status=>true, :msg=>"You have successfully followed"}
            else
              @response = {:status=>false, :msg=>"An error occurred, Please try again later."}
            end
        end
      end

    end


  end
  
  def my_profile
	@my_followers = current_user.followers
	@my_followings = current_user.following
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/followers/my_follows.html.erb
<% @my_followers.each do |my_follower| %>
	<%= my_follower.user.email %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if current_user.present? %>

  <%= link_to "All Users", users_path %>
  <%= link_to "My Profile", my_profile_path %>
  <%= link_to "My Tweets", my_tweets_path %>
  <%= link_to "My Followers", my_follows_path %>
  <%= link_to "Sign out", destroy_user_session_path	, :method => 'delete' %>
  
  
  
<% else %>
  <%= link_to "Sign Up", new_user_registration_path %> |   <%= link_to "Sign In", new_user_session_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/tweets/my_tweets.html.erb
<% if @tweets.present? %>
	<% @tweets.each do |tweet| %>
		<%= tweet.title %> <br>
	<% end %>
<% else %>
	No Tweets found
<% end %>

app/views/users/follow.js.erb
document.getElementById('flash').innerHTML = "<%= @response[:msg] %>"

app/views/users/index.html.erb
<div id ="flash"></div>

<% if @users.present? %>
	<% @users.each do |user| %>
		<%= user.email %>   <%= link_to "Follow", {:controller => "users", :action => "follow", :user_id => user.id}, :method => :post, :remote => true %> <br>
	<% end %>
<% else %>
	No Users found
<% end %>

app/views/users/my_profile.html.erb
<% if @my_followers.present? %>
	<% @my_followers.each do |my_follower| %>
		<%= my_follower.user.email%>
	<% end %>
<% else %>
	No Followers found
<% end %>

<% if @my_followings.present? %>
	<% @my_followings.each do |my_following| %>
		<%= my_follower.user.name%>
	<% end %>
<% else %>
	No Followings found
<% end %>